 [Function: model]
  hooks: Kareem { _pres: {}, _posts: {} },
  base:
   Mongoose {
     connections: [ [Object] ],
     plugins: [],
     models:
      { Challenge: [Circular],
        ChallengeImage: [Object],
        SmsCode: [Object],
        Task: [Object],
        User: [Object],
        UserChallenge: [Object] },
     modelSchemas:
      { Challenge: [Object],
        ChallengeImage: [Object],
        SmsCode: [Object],
        Task: [Object],
        User: [Object],
        UserChallenge: [Object] },
     options: { pluralization: true } },
  modelName: 'Challenge',
  model: [Function: model],
  db:
   NativeConnection {
     base:
      Mongoose {
        connections: [Object],
        plugins: [],
        models: [Object],
        modelSchemas: [Object],
        options: [Object] },
     collections:
      { challenges: [Object],
        challengeimages: [Object],
        smscodes: [Object],
        tasks: [Object],
        users: [Object],
        userchallenges: [Object] },
     models:
      { Challenge: [Circular],
        ChallengeImage: [Object],
        SmsCode: [Object],
        Task: [Object],
        User: [Object],
        UserChallenge: [Object] },
     config: { autoIndex: true },
     replica: false,
     hosts: null,
     host: 'localhost',
     port: 27017,
     user: undefined,
     pass: undefined,
     name: 'skills',
     options:
      { db: [Object],
        auth: {},
        server: [Object],
        replset: [Object],
        mongos: undefined },
     otherDbs: [],
     _readyState: 1,
     _closeCalled: false,
     _hasOpened: true,
     _listening: false,
     _events: { error: [Function: bound bound warn] },
     _eventsCount: 1,
     db:
      Db {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        s: [Object],
        serverConfig: [Getter],
        bufferMaxEntries: [Getter],
        databaseName: [Getter],
        _listening: true } },
  discriminators: undefined,
  schema:
   Schema {
     obj:
      { dt: [Object],
        skillType: [Object],
        reportType: [Object],
        title: [Object],
        shortDesc: [Object],
        fullDesc: [Object],
        price: [Object],
        periodType: [Object],
        tasks: [Object] },
     paths:
      { dt: [Object],
        skillType: [Object],
        reportType: [Object],
        title: [Object],
        shortDesc: [Object],
        fullDesc: [Object],
        price: [Object],
        periodType: [Object],
        tasks: [Object],
        _id: [Object],
        __v: [Object] },
     subpaths: {},
     virtuals: { id: [Object] },
     singleNestedPaths: {},
     nested: {},
     inherits: {},
     callQueue: [ [Object], [Object], [Object], [Object] ],
     _indexes: [],
     methods: {},
     statics: {},
     tree:
      { dt: [Object],
        skillType: [Object],
        reportType: [Object],
        title: [Object],
        shortDesc: [Object],
        fullDesc: [Object],
        price: [Object],
        periodType: [Object],
        tasks: [Object],
        _id: [Object],
        id: [Object],
        __v: [Function: Number] },
     _requiredpaths: [ 'title', 'dt' ],
     discriminatorMapping: undefined,
     _indexedpaths: [],
     query: {},
     childSchemas: [],
     s: { hooks: [Object], kareemHooks: [Object] },
     options:
      { retainKeyOrder: false,
        typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strict: true,
        pluralization: true },
     '$globalPluginsApplied': true },
  collection:
   NativeCollection {
     collection: Collection { s: [Object] },
     opts: { bufferCommands: true, capped: false },
     name: 'challenges',
     collectionName: 'challenges',
     conn:
      NativeConnection {
        base: [Object],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        hosts: null,
        host: 'localhost',
        port: 27017,
        user: undefined,
        pass: undefined,
        name: 'skills',
        options: [Object],
        otherDbs: [],
        _readyState: 1,
        _closeCalled: false,
        _hasOpened: true,
        _listening: false,
        _events: [Object],
        _eventsCount: 1,
        db: [Object] },
     queue: [],
     buffer: false,
     emitter:
      EventEmitter {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  Query:
   { [Function]
     base:
      Query {
        toConstructor: [Function: toConstructor],
        setOptions: [Function],
        collection: [Function: collection],
        '$where': [Function],
        where: [Function],
        equals: [Function: equals],
        eq: [Function: eq],
        or: [Function: or],
        nor: [Function: nor],
        and: [Function: and],
        gt: [Function],
        gte: [Function],
        lt: [Function],
        lte: [Function],
        ne: [Function],
        in: [Function],
        nin: [Function],
        all: [Function],
        regex: [Function],
        size: [Function],
        maxDistance: [Function],
        minDistance: [Function],
        mod: [Function],
        exists: [Function],
        elemMatch: [Function],
        within: [Function: within],
        box: [Function],
        polygon: [Function],
        circle: [Function],
        near: [Function: near],
        intersects: [Function: intersects],
        geometry: [Function: geometry],
        select: [Function: select],
        slice: [Function],
        sort: [Function],
        limit: [Function],
        skip: [Function],
        maxScan: [Function],
        batchSize: [Function],
        comment: [Function],
        maxTime: [Function],
        snapshot: [Function],
        hint: [Function],
        slaveOk: [Function],
        read: [Function],
        tailable: [Function],
        merge: [Function],
        find: [Function],
        cursor: [Function: cursor],
        findOne: [Function],
        count: [Function],
        distinct: [Function],
        update: [Function: update],
        updateMany: [Function: updateMany],
        updateOne: [Function: updateOne],
        remove: [Function],
        findOneAndUpdate: [Function],
        findOneAndRemove: [Function],
        _findAndModify: [Function],
        _wrapCallback: [Function],
        setTraceFunction: [Function],
        exec: [Function: exec],
        thunk: [Function],
        then: [Function],
        stream: [Function],
        selected: [Function: selected],
        selectedInclusively: [Function: selectedInclusively],
        selectedExclusively: [Function: selectedExclusively],
        _mergeUpdate: [Function],
        _optionsForExec: [Function],
        _fieldsForExec: [Function],
        _updateForExec: [Function],
        _ensurePath: [Function],
        _validate: [Function] } },
  '$__insertMany': [Function],
  insertMany: [Functio